In [1]:
#Function Transformer

In [2]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np


# create a dataset
x  = np.array([[1,2],[3,4]])


# define thee transformation function
log_transform =FunctionTransformer(np.log1p)




#apply the transformer to the dataset
x_transformed = log_transform.transform(x)

print(x_transformed)

[[0.69314718 1.09861229]
 [1.38629436 1.60943791]]


In [3]:

# Practical use case


In [5]:
#1. Custom feature engineering
from sklearn.preprocessing import FunctionTransformer
import pandas as pd




x =np.array([[1,2],[3,4]])

def holi(x):
  return np.hstack((x,x**2))


# apply the funtion transformrt to apply the custom fucniton
custom_transformer= FunctionTransformer(holi)

# apply the transformer to the input data
x_transformed = custom_transformer.transform(x)

print(x_transformed)


[[ 1  2  1  4]
 [ 3  4  9 16]]


In [8]:
# 2. Scaling and normalisation


# create a dataset
x = np.array(([1,2],[3,4]))

# define the custom scoring function
def my_scaling(x):
  return x/np.max(x)

custom_transformer=FunctionTransformer(my_scaling)


x_transformed= custom_transformer.transform(x)

print(x_transformed)

[[0.25 0.5 ]
 [0.75 1.  ]]


In [9]:
#3. Data cleaning

x =np.array([[1,2],[3,4]])

def my_cleaning(x):
  x[np.isnan(x)]=0
  return x

custom_transformer = FunctionTransformer(my_cleaning)

x_transformed = custom_transformer.transform(x)

print(x_transformed)

[[1 2]
 [3 4]]


In [10]:
df = pd.read_csv("placement.csv")

In [11]:
df.head(5)

,cgpa,resume_score,placed
0,8.14,6.52,1
1,6.17,5.17,0
2,8.27,8.86,1
3,6.88,7.27,1
4,7.52,7.30,1


In [12]:
df.isnull().sum()

,0
cgpa,0
resume_score,0
placed,0


In [13]:
x =df.drop(columns = ['placed'])

In [14]:
y=df['placed']

In [15]:
from sklearn.preprocessing import FunctionTransformer

In [18]:
log_transform = FunctionTransformer(np.log1p)
# apply the transformation to the dataset
x_transformed = log_transform.transform(x)

In [19]:
x_transformed

,cgpa,resume_score
0,1.167099,1.104451
1,1.088530,1.036630
2,1.171486,1.190427
3,1.119828,1.135469
4,1.144992,1.136632
...,...,...
95,1.095934,1.098203
96,1.170145,1.153793
97,1.110114,1.154512
98,1.167099,1.061812


In [ ]:
print()