In [1]:
import numpy as np

In [5]:
a = [1,34,89]
type(a)

list

In [7]:
b = np.array(a)
b

array([ 1, 34, 89])

In [9]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b= np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
print("total rows and columns:",b.shape)
print("total elements:",b.size)
print("dimension of an array:",b.ndim)

total rows and columns: (3, 3)
total elements: 9
dimension of an array: 2


In [16]:
a = []
size = int(input("enter size:"))
for i in range(size):
    val = int(input("enter item:"))
    a.append(val)
b =np.array(a)
b

enter size: 4
enter item: 67
enter item: 8
enter item: 46
enter item: 9


array([67,  8, 46,  9])

In [11]:
type(b)

numpy.ndarray

In [13]:
#zeros method
a= np.zeros(3)
a

array([0., 0., 0.])

In [15]:
b= np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
#ones method
a= np.ones(4)
a

array([1., 1., 1., 1.])

In [19]:
a= np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
#eye method      #assymetric matrix
np.eye(3,4)      

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [23]:
np.eye(3)         #symmetric matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#diagonal meth
np.diag([1,4,56,4])

array([[ 1,  0,  0,  0],
       [ 0,  4,  0,  0],
       [ 0,  0, 56,  0],
       [ 0,  0,  0,  4]])

In [27]:
#random module

np.random.randint(1,10,4)

array([3, 7, 7, 4])

In [7]:
np.random.rand(5)

array([0.30177205, 0.86520525, 0.61018904, 0.61282455, 0.49278944])

In [31]:
np.random.seed(11)                                          
a=np.random.randint(1,10,3)
a

array([1, 2, 8])

## view vs copy

In [34]:
#view meth

a = np.array([10,20,30,40,50,60,70,80,90])
b=a[2:6]
b[:]=0
b
a

array([10, 20,  0,  0,  0,  0, 70, 80, 90])

In [36]:
#copy meth
a = np.array([10,20,30,40,50,60,70,80,90])
b=a[2:6].copy()
b[:]=0
b

array([0, 0, 0, 0])

In [38]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
#reshaping the array 

a= np.random.randint(1,100,12)
a

array([15, 72, 73, 24, 87, 24, 14, 42, 19, 13, 47, 48])

In [17]:
a.reshape(2,6)

array([[15, 72, 73, 24, 87, 24],
       [14, 42, 19, 13, 47, 48]])

In [19]:
a.reshape(6,2)

array([[15, 72],
       [73, 24],
       [87, 24],
       [14, 42],
       [19, 13],
       [47, 48]])

In [21]:
a.reshape(3,4)

array([[15, 72, 73, 24],
       [87, 24, 14, 42],
       [19, 13, 47, 48]])

In [23]:
a.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [51]:
a= np.random.randint(1,60,36)
a

array([13,  2, 11, 38, 54, 40, 21, 18, 28, 25, 57, 18,  4,  7, 44, 51, 51,
        1, 16, 33, 24, 28,  7, 26, 44, 11, 58, 28, 45, 54, 15,  8, 56, 16,
        1, 41])

In [53]:
a.reshape(6,6)

array([[13,  2, 11, 38, 54, 40],
       [21, 18, 28, 25, 57, 18],
       [ 4,  7, 44, 51, 51,  1],
       [16, 33, 24, 28,  7, 26],
       [44, 11, 58, 28, 45, 54],
       [15,  8, 56, 16,  1, 41]])

In [55]:
a.reshape(1,36)

array([[13,  2, 11, 38, 54, 40, 21, 18, 28, 25, 57, 18,  4,  7, 44, 51,
        51,  1, 16, 33, 24, 28,  7, 26, 44, 11, 58, 28, 45, 54, 15,  8,
        56, 16,  1, 41]])

In [57]:
a.reshape(9,4)

array([[13,  2, 11, 38],
       [54, 40, 21, 18],
       [28, 25, 57, 18],
       [ 4,  7, 44, 51],
       [51,  1, 16, 33],
       [24, 28,  7, 26],
       [44, 11, 58, 28],
       [45, 54, 15,  8],
       [56, 16,  1, 41]])

In [59]:
a.reshape(18,2)

array([[13,  2],
       [11, 38],
       [54, 40],
       [21, 18],
       [28, 25],
       [57, 18],
       [ 4,  7],
       [44, 51],
       [51,  1],
       [16, 33],
       [24, 28],
       [ 7, 26],
       [44, 11],
       [58, 28],
       [45, 54],
       [15,  8],
       [56, 16],
       [ 1, 41]])

In [61]:
# conditional selection in numpy

In [67]:
a =np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [69]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [71]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [73]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [75]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [81]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [83]:
a+b

array([[ 6,  8],
       [10, 12]])

In [85]:
a-b

array([[-4, -4],
       [-4, -4]])

In [87]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [93]:
#linspace() method
a= np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [99]:
#unique() method
# np.unique(arr , return_index =True , return_counts =True)

In [101]:
a =np.array([1,2,2,2,1,3,4,3,2,2,5])
np.unique(a, return_index= True, return_counts = True)

(array([1, 2, 3, 4, 5]),
 array([ 0,  1,  5,  6, 10], dtype=int64),
 array([2, 5, 2, 1, 1], dtype=int64))

In [110]:
a= np.random.randint(1,10,9).reshape(3,3)
a

array([[6, 7, 2],
       [3, 1, 1],
       [9, 9, 5]])

In [116]:
np.sum(a , axis=0)    # col wise operation in numpy

array([18, 17,  8])

In [120]:
np.sum(a,axis =1)     # row wise operation in numpy

array([15,  5, 23])

In [122]:
np.sum(a)

43

In [124]:
# Hstack() and vstack()  

In [126]:
a= np.arange(1,5)
a

array([1, 2, 3, 4])

In [130]:
b=np.arange(5,9)
b

array([5, 6, 7, 8])

In [132]:
c=np.arange(9,13)
c

array([ 9, 10, 11, 12])

In [134]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [143]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])